name: Build and Deploy
on:
  push:
    branches:
      - feature/morishita

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy for Function
        uses: w9jds/firebase-action@master
        with:
          args: deploy --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      # - name: Deploy to Firebase
      #   run: |
      #     node_modules/firebase-tools/lib/bin/firebase.js deploy --token $FIREBASE_TOKEN
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
